In [1]:
#NLTK Training (Numpy)

message = 'alex'
print(message)

alex


In [5]:
name = input("What is your name?")
print('Hello', name)

What is your name?alex
Hello alex


In [8]:
#Slicing 
subjects = ['math', 'science', 'health', 'programming']

subjects [1:] #access all elements starting from items at index 1(which is the 2nd element)

['science', 'health', 'programming']

In [9]:
subjects [1:3] #access all elements starting from items at index 1 up to item in index (which is the 2nd element)

['science', 'health']

In [0]:
#Dictionary
scientist = {'Name': 'Allan Turing', 'Field': 'Mathematics'}

In [11]:
print('Name', scientist['Name'])

Name Allan Turing


In [0]:
scientist['Field'] = 'Mathematics', 'Computer Science', 'Biology'

In [13]:
len(scientist)

2

In [14]:
scientist.keys()

dict_keys(['Name', 'Field'])

In [19]:
import numpy as np
#create an array
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [27]:
#Create a zero array
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [26]:
#Create a one Array
b = np.ones((2, 2))
print(b)

[[1. 1.]
 [1. 1.]]


In [23]:
#Create a random Array
c = np.random.randint(10, size = (5))
print(c)

[5 6 5 8 5]


In [24]:
#Create a random Array
d = np.random.randint(10, size = (5))
print(d)

[8 4 1 1 3]


In [25]:
p = c + d
print(p)

[13 10  6  9  8]


In [30]:
#Create a random float array
e = np.random.random((2, 2))
print(e)

[[0.14024507 0.65095446]
 [0.68591418 0.31497532]]


In [0]:
#Matrix multiply
np.dot(x,y)
x.dot(y)
y.dot(x)

In [0]:
#returns index of max value
np.argmax(x, axis = 1) #getting the max value at index 1
np.argmax(y, axis = 0) #getting the max value at index 0

In [0]:
#For iteration over an array x
for number in x:
  print(number, end = '')# printing a number with space as between

In [0]:
#how to see the type of data in array
#array.dtype
#or as parameter -> dtype = "desired type of data"

In [33]:
x = np.array([[1,2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis = 0)) #getting the sum value at each column
print(np.sum(x, axis = 1)) #getting the sum value at each row


10
[4 6]
[3 7]


In [51]:
#Exercise at Numpy Programming 
A = np.array([[25, 5, 16, 9], [13, 20, 19, 0], [5, 9, 1, 16], [27, 13, 15, 19]])
B = np.array([[10, 5, 20, 20], [5, 21, 22, 27], [26, 19, 22, 3], [27, 8, 18, 7]])
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.dot(A, B))
print(np.add(c, d))
print(np.subtract(c, d))
print(np.multiply(c, d))
print(np.dot(c, d))
print(np.add(A, 10))
print(np.add(B, 10))
print(np.add(c, 15))
print(np.add(d, 15))
print(np.add((np.multiply(2, A)),(np.multiply(2, B))))
print(np.multiply((np.add(A, B)), 3))
print(np.multiply((A - B + A - B + B ), 4))

[[35 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
[[ 15   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
[[250  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]
[[ 934  606 1124  746]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
2298
[[35 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]
[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
[[ 70  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]
[[105  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]
[[ 160   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]


In [0]:
#NLTK
#Sentiment Classification